First dz
ok-technopolis-2020/Schur_Saveliy pull request #1
Opened 2020-10-08 14:48 UTC by SaveliyShur

2020-10-09 11:56 UTC, fromanywhere requested changes
ARIA!

2020-10-09 11:56 UTC, fromanywhere commented on todos.html
> +        <h1 align="center" class="todos">todos</h1>
презентационные атрибуты не нужны

2020-10-09 11:56 UTC, fromanywhere commented on todos.html
> +        <form>
Тут нужно подумать, а будем ли мы вообще когда-нибудь отправлять эту форму, и если будем, то как

2020-10-09 11:56 UTC, fromanywhere commented on todos.html
> +            <p>What needs to be done?</p>
Ну, нет, тут кнопка и поле ввода

2020-10-09 11:56 UTC, fromanywhere commented on todos.html
> +            <p><input type="radio" name="answer" value="HTML">HTML <span class="close"></span></p>
Нужно больше иерархии! сейчас очень плоско и не структтурировано

2020-10-09 11:56 UTC, fromanywhere commented on todos.html
> +            <p><input type="radio" name="answer" value="CSS">CSS <span class="close"></span></p>
Удаление — кнопка

2020-10-09 11:56 UTC, fromanywhere commented on todos.html
> +            <p><input type="radio" name="answer" value="JS">JS <span class="close"></span></p>
Галочка — чекбокс, не радио

2020-10-09 11:56 UTC, fromanywhere commented on todos.html
> +            <p><br></p>
ну, нет, ни абзаца, ни переноса строки тут нет

2020-10-09 11:56 UTC, fromanywhere commented on todos.html
> +                <button class="All">All</button>
здесь разные области управления: есть фильтр из трех состояний, это радиокнопки, а отдельно от них кнопка с удалением

2020-10-13 14:33 UTC, SaveliyShur commented
Исправил по материалам лекции, получилось не совсем так как на картинке, надо ли добавлять переносы строки?

2020-10-13 14:53 UTC, SaveliyShur commented
Добавил список

2020-10-13 17:01 UTC, fromanywhere requested changes

2020-10-13 17:01 UTC, fromanywhere commented on todos.html
> +                                    <button class="delete_item">X</button>
Как минимум тут нужно будет вынести кнопку из-под лейбла, потому что сейчас непонятно, к чему приведет клик — к выбору элемента или к нажатию кнопки

2020-10-13 19:46 UTC, SaveliyShur commented on todos.html
> +                                    <button class="delete_item">X</button>
Вынес, ее надо в div оборачивать? Если в разметки элементы на разных строках получаются, то эту проблему должен css решать?

2020-10-13 20:03 UTC, fromanywhere commented on todos.html
> +                                    <button class="delete_item">X</button>
Да

2020-10-13 20:03 UTC, fromanywhere approved these changes

2020-10-13 20:09 UTC, SaveliyShur commented on todos.html
> +                                    <button class="delete_item">X</button>
Готово

2020-10-13 23:45 UTC, merged