Task2
ok-technopolis-2020/Schur_Saveliy pull request #2
Opened 2020-11-21 22:41 UTC by SaveliyShur

2020-11-22 11:19 UTC, fromanywhere requested changes

2020-11-22 11:19 UTC, fromanywhere commented on styles/footer.css
> +.action_bar {
какой-то бэм не бэм

2020-11-22 11:19 UTC, fromanywhere commented on styles/header.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap");
мы тут с другими студентами наткнулись, что потом цссный импорт не очень удобно натягивается на parcel

2020-11-22 11:19 UTC, fromanywhere commented on styles/main.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap");
и не понадобится в каждом файле заново импортировать

2020-11-22 11:19 UTC, fromanywhere commented on styles/main.css
> +    -webkit-appearance: none;
префиксы не нужны

2020-11-22 11:19 UTC, fromanywhere commented on styles/main.css
> +    border: none;
Я могу принять Ваше нежелания растягивать по высоте, но вот так по горизонтали дырки оставлять — это вообще нехорошо 
![image](https://user-images.githubusercontent.com/1042969/99902154-a948c080-2ccc-11eb-8d0d-511857945926.png)

2020-11-22 11:19 UTC, fromanywhere commented on styles/main.css
> +    background: no-repeat center white url(/assets/done-not-active.svg);
у нас тут нет локального сервера, так не разрезолвится. По идее ./assets заработает и под сервером, и с файловой системы

2020-11-22 11:19 UTC, fromanywhere commented on styles/main.css
> +    top: -20%;
почему 20%?

2020-11-22 11:19 UTC, fromanywhere commented on styles/main.css
> +    height: 24px;
увеличиваем площадь клика

2020-11-22 11:19 UTC, fromanywhere commented on styles/main.css
> +    border-color: tomato;
на фокус тоже надо показывать

2020-11-22 11:19 UTC, fromanywhere commented on styles/main.css
> +    position: relative;
упс 
![image](https://user-images.githubusercontent.com/1042969/99902199-1197a200-2ccd-11eb-904e-eb75f16b4e67.png)

2020-11-22 11:19 UTC, fromanywhere commented on styles/footer.css
> +    color: #888888;
нейминг отвалился, поэтому мимо макета всё 
![image](https://user-images.githubusercontent.com/1042969/99902215-2e33da00-2ccd-11eb-8ada-8e1463b2a936.png)

2020-11-22 11:19 UTC, fromanywhere commented on styles/root.css
> +  display: grid;
зарезается левый край из-за такого на узких экранах. min-width спасет 
![image](https://user-images.githubusercontent.com/1042969/99902230-4e639900-2ccd-11eb-9bab-2c5adc9b3adf.png)

2020-11-22 11:19 UTC, fromanywhere commented on styles/header.css
> +      font-weight: 100;
бонусное задание — понять, почему не работает так

2020-11-23 23:40 UTC, SaveliyShur commented on styles/main.css
> +    position: relative;
Пока это нормально не решилось, за рамку не выходит и даже в центре остается, с переносами, но вот другие части тогда ломаются

2020-12-21 10:06 UTC, fromanywhere commented
Тут конечно всё ползет но допустим в целом задача решена 
![image](https://user-images.githubusercontent.com/1042969/102764675-91786100-438c-11eb-8925-02c5fdf706fa.png)

Хотя нейминг всё еще ползет, и верстка айтема принципиально так себе. Там конечно должно быть что-то в духе

`    display: flex;
    align-items: center;
    padding: 16px 0;`

2020-12-21 10:06 UTC, fromanywhere approved these changes

2021-03-22 11:51 UTC, closed without merging